config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :auto_complete_cities, only: [:index]
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :index, :destroy ]
    resources :rewards, only: [ :index ] do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :details, to: 'projects/contribution_details#index'
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'about_mobile'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'trash'
        put 'request_refund'
        put 'chargeback'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route, allow_nil: true


    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
  end
end

app/models/concerns/project/error_groups.rb
module Project::ErrorGroups
  extend ActiveSupport::Concern

  included do
    begin
      ATTR_GROUPS = {
        basics: [:name, :permalink, :category_id, :city],
        goal: [:goal, :online_days],
        description: [:about_html],
        budget: [:budget],
        card: [:uploaded_image, :headline],
        video: [:video_url],
        reward: [:'rewards.size', :'rewards.minimum_value', :'rewards.deliver_at'],
        user_about: [:'user.uploaded_image', :'user.name', :'user.about_html'],
        user_settings: ProjectAccount.attribute_names.map{|attr| ('project_account.' + attr).to_sym} << :account << :'account.agency_size'
      }
    rescue Exception => e
      puts "problem while using ErrorGroups concern:\n '#{e.message}'"
    end

    def error_included_on_group? error_attr, group_name
      Project::ATTR_GROUPS[group_name.to_sym].include?(error_attr)
    end

    def has_errors_for?(field)
      errors.include?(field)
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash!
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    params.require(:project).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contribution_details_controller.rb
class Projects::ContributionDetailsController < ApplicationController
  has_scope :was_confirmed, type: :boolean
  has_scope :pending, type: :boolean
  has_scope :page, default: 1

  def index
    render collection
  end

  def collection
    @contributions ||= apply_scopes(parent.contribution_details).available_to_display.order("created_at DESC").per(10)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: 10)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.referral_link = referral_link
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def second_slip
    authorize resource
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  after_filter :verify_authorized, except: %i[index destroy]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @posts ||= policy_scope(parent.posts).ordered
    render @posts.page(params[:page]).per(3)
  end

  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects/reminders_controller.rb
class Projects::RemindersController < ApplicationController
  before_filter :authenticate_user!

  def create
    unless current_user.has_valid_contribution_for_project?(params[:id])
      reminder_at = project.expires_at - 48.hours
      project.notify_once(:reminder, current_user, project, {deliver_at: reminder_at})
    end

    flash[:notice] = t('projects.reminder.ok')
    redirect_to project_by_slug_path(project.permalink)
  end

  def destroy
    project.delete_from_reminder_queue(current_user.id)
    redirect_to project_by_slug_path(project.permalink)
  end

  protected

  def project
    @project ||= Project.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  after_filter :verify_authorized, except: %i[index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit show]

  has_scope :pg_search, :by_category_id, :near_of
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url, :resource, :collection

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  def index
    respond_to do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
      end
      format.atom do 
        return render layout: false, locals: {projects: projects}
      end
      format.rss { redirect_to projects_path(format: :atom), :status => :moved_permanently }
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new
    @project.attributes = permitted_params.merge(user: current_user, referral_link: referral_link)
    authorize @project
    if @project.save
      redirect_to edit_project_path(@project, anchor: 'home')
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis, :analysis_success
  end

  def publish
    authorize resource
    resource_action :push_to_online
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.attributes = permitted_params

    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true, ref: (params[:ref] || 'embed')}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  def about_mobile
    resource
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?
    @budget = resource.budgets.build

    resource.build_account unless resource.account
  end

  def resource_action action_name, success_redirect=nil
    if resource.send(action_name)
      if referral_link.present?
        resource.update_attribute :referral_link, referral_link
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      if success_redirect
        redirect_to edit_project_path(@project, anchor: success_redirect)
      else
        redirect_to edit_project_path(@project, anchor: 'home')
      end
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    render partial: 'projects/card',
      collection: projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects
    page = params[:page] || 1
    @projects ||= apply_scopes(Project.visible.order_status).
      most_recent_first.
      includes(:project_total, :user, :category).
      page(page).per(18)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/projects/_dashboard_basics.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
              = @project.display_errors(:basics)
              - if (current_user && current_user.admin?)
                = form.input :user_id, as: :string, 
                  wrapper: :two_columns,
                  wrapper_class: 'w-row u-marginbottom-20 card card-terciary medium',
                  label_wrapper_html: { class: 'w-col w-col-5' },
                  text_field_wrapper_html: { class: 'w-col w-col-7' },
                  input_html: { class: 'positive medium', required: true },
                  validation_text: false

              = form.input :name, as: :string, 
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7 w-sub-col' },
                input_html: { class: 'positive medium', required: true, maxlength: Project::NAME_MAXLENGTH },
                validation_text: false

              = form.input :permalink, as: :string, 
                wrapper: :two_columns_with_postfix,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7 w-sub-col' },
                input_html: { class: 'postfix positive medium', required: true },
                field_wrapper_html: { class: 'w-col w-col-8 w-col-small-6 w-col-tiny-6' },
                validation_text: false,
                preppend_text_wrapper_html: { class: 'w-col w-col-4 w-col-small-6 w-col-tiny-6 text-field prefix no-hover medium prefix-permalink' },
                preppend_input_text: 'www.catarse.me/',
                preppend_input_text_wrapper_html: { class: 'fontcolor-secondary u-text-center fontsize-smallest' }

              = form.association :category, as: :select, 
                collection: Category.order(:name_pt),
                prompt: t('simple_form.prompts.project.category'),
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7' },
                input_html: { class: 'w-select text-field positive medium', required: true },
                validation_text: false

              #city-input-wrapper data-searchpath=auto_complete_cities_path
                .w-row.u-marginbottom-30.card.card-terciary.medium
                  .w-col.w-col-5.w-sub-col
                    label.fontweight-semibold.fontsize-base=t('.city')
                    label.field-label.fontsize-smallest.fontcolor-secondary=t('simple_form.hints.project.city')
                  .w-col.w-col-7
                    = text_field_tag :city_name, ( @project.city.show_name if @project.city ), class: 'string optional w-input text-field w-input text-field positive city-search-input', autocomplete: "off"
                    input#project_city_id.w-hidden name="project[city_id]" type="text" /
                    .table-outer.search-pre-result.w-hidden

    .section
      .w-container
        .w-row
          .w-col.w-col-4.w-col-push-4
            = hidden_field_tag 'anchor', 'basics'
            = form.button :submit, t('.form.submit'), class:'btn btn-large', id: 'basics-save'

app/views/catarse_bootstrap/projects/_dashboard_budget.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
            = @project.display_errors(:budget)
            = form.input :budget, as: :text,
              wrapper: :two_columns,
              wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
              input_html: { class: 'redactor positive', required: false },
              validation_text: false
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'budget'
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_card.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-8
          .w-form
              = @project.display_errors(:card)
              = form.input :uploaded_image, as: :file,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-6' },
                input_html: { required: false },
                validation_text: false

              = form.input :headline, as: :text,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7' },
                input_html: { class: 'positive', rows: 3, required: false, maxlength: Project::HEADLINE_MAXLENGTH },
                validation_text: false
        .w-col.w-col-4
          = render 'card'
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'card'
          = form.hidden_field :project_id, value: @project.id
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_nav.html.slim
- edit = defined?(edit_page) || false
= content_for :body_class, 'body-project open'
#project-nav
  .project-nav-wrapper
    nav.w-section.dashboard-nav.side
      = link_to (@project.published? ? project_by_slug_path(@project.permalink) : '#preview'), id: 'dashboard_preview_link', class: 'w-inline-block dashboard-project-name' , data: {target: '#dashboard_preview', tab_group: 'edit'} do
        - if @project.uploaded_image.present?
          img.thumb-project-dashboard src="#{@project.display_image(:project_thumb_large)}" width="114"
        - else
          img.thumb-project-dashboard src="#{image_path('thumb-project.png')}" width="114"
        .fontcolor-negative.lineheight-tight.fontsize-small= @project.name

      #info-links
        = link_to (edit ? '#home' : edit_project_path(@project, anchor: 'home')), id: 'dashboard_home_link', class: 'dashboard-nav-link-left ' , data: {target: '#dashboard_home', tab_group: 'edit'} do
          span.fa.fa-bar-chart.fa-lg.fa-fw
          = t('.start_tab')
        - if @project.published?
          = link_to (edit ? '#reports' : edit_project_path(@project, anchor: 'reports')), id: 'dashboard_reports_link', class: 'dashboard-nav-link-left ' , data: {target: '#dashboard_reports', tab_group: 'edit'} do
            span.fa.fa.fa-table.fa-lg.fa-fw
            = t('.reports_tab')
          = link_to (edit ? '#posts' : edit_project_path(@project, anchor: 'posts')), id: 'dashboard_posts_link', class: 'dashboard-nav-link-left u-marginbottom-30' , data: {target: '#dashboard_posts', tab_group: 'edit'} do
            span.fa.fa-bullhorn.fa-fw.fa-lg
            = t('.posts_tab')
            | &nbsp
            span.badge= @project.posts.count

      .edit-project-div
        - if @project.published?
          button#toggle-edit-menu.dashboard-nav-link-left
            span.fa.fa-pencil.fa-fw.fa-lg
            = t('.edit_project')
          #edit-menu-items.w-hidden
            = render partial: 'dashboard_nav_links', locals: {edit: edit}
        - else
          = render partial: 'dashboard_nav_links', locals: {edit: edit}

          .btn-send-draft-fixed
            - if @project.draft?
               = link_to t('.send'), send_to_analysis_project_path(@project), class: 'btn btn-medium'
            - if @project.approved?
               = link_to publish_project_path(@project), class: 'btn btn-medium' do
                = t('.publish')
                | &nbsp;&nbsp;
                span.fa.fa-chevron-right
  a.btn-dashboard href="#"
    span.fa.fa-bars.fa-lg

app/views/catarse_bootstrap/projects/_dashboard_reports.html.slim
- selected_r = @project.selected_rewards
.section.project-metrics
  .w-container
    .w-row
      .w-col.w-col-2
      .w-col.w-col-8
        .card.u-radius.u-marginbottom-20.card-terciary data-ix="new-interaction" 
          .fontsize-small.fontweight-semibold.u-marginbottom-20
            span.fa.fa-download &nbsp;
            | Baixar relatórios
          ul.w-list-unstyled
            li.fontsize-smaller.u-marginbottom-10
              div
                | partidarios confirmado &nbsp;
                = link_to 'CSV', reports_contribution_reports_for_project_owners_path(project_id: @project.id, format: :csv), class: 'alt-link'
                | &nbsp;\&nbsp;
                = link_to 'XLS', reports_contribution_reports_for_project_owners_path(project_id: @project.id, format: :xls), class: 'alt-link'
            li.divider.u-marginbottom-10
            li.fontsize-smaller.u-marginbottom-10
              div
                | partidarios destacados&nbsp;&nbsp;
                = link_to 'CSV', reports_contribution_reports_for_project_owners_path(project_id: @project.id, state: 'pending', waiting_payment: 'true', format: :csv), class: 'alt-link'
                | &nbsp;\&nbsp;
                = link_to 'XLS', reports_contribution_reports_for_project_owners_path(project_id: @project.id, state: 'pending', waiting_payment: 'true', format: :xls), class: 'alt-link'
            li.divider.u-marginbottom-10
            li.fontsize-smaller.u-marginbottom-10
              div
                | Recompensa partidarios no seleccionado&nbsp;&nbsp;
                = link_to 'CSV', reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: 0, format: :csv), class: 'alt-link'
                | &nbsp;\&nbsp;
                = link_to 'XLS', reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: 0, format: :xls), class: 'alt-link'
            li.divider.u-marginbottom-10
            - if selected_r.length > 0
                - selected_r.each do |reward|
                  li.fontsize-smaller.u-marginbottom-10
                    div
                      | Los partidarios de recompensa #{reward.display_minimum} &nbsp;
                      = link_to 'CSV', reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: reward.id, format: :csv), class: 'alt-link'
                      | &nbsp;\&nbsp;
                      = link_to 'XLS', reports_contribution_reports_for_project_owners_path(project_id: @project.id, reward_id: reward.id, format: :xls), class: 'alt-link'
                  li.divider.u-marginbottom-10
      .w-col.w-col-2

app/views/catarse_bootstrap/projects/_project_embed.html.slim
- box_width = "300px"
- box_height = "314px"

.w-row.card.card-terciary.u-marginbottom-20
  .w-col.w-col-6.w-sub-col
    .fontweight-semibold.u-marginbottom-20.fontsize-small= t('.insert')
    .w-form
      = text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '" scrolling="no"></iframe>', class: 'w-input text-field ', readonly: true, rows: 5
  .w-col.w-col-6
    iframe frameborder="0" height=box_height src=embed_project_url(@project) width=box_width scrolling="no"